fix error on service estimations
Autofleet/locomotion pull request #266
Opened 2022-07-07 16:07 UTC by lieblichaaron

## ℹ️ Change description:
Nothing here

<details><summary><sub>templates<sub></summary>
<p>
  
<sub>[templates: [bug](?expand=1&template=bug.md), [feature](?expand=1&template=feature.md)]</sub>

</p>
</details>

2022-07-07 16:20 UTC, OmerGery approved these changes

2022-07-07 16:20 UTC, OmerGery commented on examples/client/Locomotion/src/context/newRideContext/index.tsx
> -    } finally {
isnt finally doing the same thing?

2022-07-10 06:44 UTC, avivbarniv commented on examples/client/Locomotion/src/context/newRideContext/index.tsx
> +      setIsLoading(false);
Finally should do the same

2022-07-10 06:44 UTC, avivbarniv commented on examples/client/Locomotion/src/context/newRideContext/index.tsx
> +  useEffect(() => {
shouldn't be related to the ride page context, please handle it in the component

2022-07-10 06:45 UTC, avivbarniv commented on examples/client/Locomotion/src/context/newRideContext/index.tsx
> +  }, [serviceRequestFailed]);
I don't like that we have specific variable for the popup, It should be a popup name

2022-07-10 06:45 UTC, avivbarniv requested changes
/

2022-07-10 08:55 UTC, avivbarniv approved these changes
Add also type of the popup, u can see notes/payment as a reference

2022-07-10 10:14 UTC, merged