fix text color
Autofleet/locomotion pull request #470
Opened 2022-07-31 16:33 UTC by lieblichaaron

## ℹ️ Change description:
Nothing here

<details><summary><sub>templates<sub></summary>
<p>
  
<sub>[templates: [bug](?expand=1&template=bug.md), [feature](?expand=1&template=feature.md)]</sub>

</p>
</details>

2022-07-31 17:54 UTC, avivbarniv reviewed
This is changing only the text color of the times, not the title for example

2022-07-31 18:00 UTC, OfryL requested changes

2022-07-31 18:00 UTC, OfryL commented on examples/client/Locomotion/src/pages/ActiveRide/RideDrawer/RideOptions/RideButtons/index.tsx
> +          textColor={colorScheme === 'dark' ? '#ffffff' : '#333333'}
use theme provider for this...
I already made some preparations there

2022-08-01 07:32 UTC, OfryL approved these changes

2022-08-01 16:29 UTC, merged