Fix compass no network issue
Autofleet/locomotion pull request #716
Opened 2023-03-22 15:05 UTC by OmerGery

We want the confirm button to be disabled until the new location is properly reverse geocoded + saved,
This logic caused the confirm button to be enabled before that
This is handle [here](https://github.com/Autofleet/locomotion/blob/17c6195a6c5570cf2e281d97bc1360702856ac4b/examples/client/Locomotion/src/pages/ActiveRide/newMap.js#L330) already - only after network is available.

2023-03-22 15:27 UTC, avivbarniv reviewed
who changes it to false atm?

2023-03-22 15:31 UTC, OmerGery commented
> who changes it to false atm?
This is handle [here](https://github.com/Autofleet/locomotion/blob/17c6195a6c5570cf2e281d97bc1360702856ac4b/examples/client/Locomotion/src/pages/ActiveRide/newMap.js#L330) already - only after network is available.

2023-03-22 15:33 UTC, avivbarniv approved these changes
change base branch

2023-03-26 09:41 UTC, sephina approved these changes

2023-03-26 10:49 UTC, avivbarniv requested changes
Why is it part of the context?
the setpickup is a local variable that scoped only to the activeRide page, it shouldn't be part of the context

2023-03-26 12:03 UTC, avivbarniv commented on examples/client/Locomotion/src/pages/ActiveRide/index.js
> +  useEffect(() => {
remov eit

2023-03-26 12:04 UTC, avivbarniv commented on examples/client/Locomotion/src/pages/ActiveRide/index.js
> +      setPickupChanged(true);
setPickupChanged(currentBsPage === BS_PAGES.CONFIRM_PICKUP)

2023-03-26 12:04 UTC, avivbarniv approved these changes

2023-03-26 14:18 UTC, merged